# Generated by Django 4.2.19 on 2025-02-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_image',
            field=models.ImageField(default='cover.jpg', null=True, upload_to='products'),
        ),
    ]
